apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: md4vcq2zb-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/md4vcq2zb-dotnet-basic-gitops